"""`music/catalogue.yaml` — the wiki, the lyrics and the audio joined into the file the station reads.

Everything the music job has produced is written for a person: nine genre files of prose, albums of
lyrics, a folder of mp3s. **Nothing downstream reads any of it.** `make music-sync` ingests one file
in the shape ARCHITECTURE §17a fixes, and this is the pass that produces it. Until it exists the
wiki is inert — a presenter cannot say the record playing was cut in a committee chamber, because
nothing has joined the fact to the file.

**Three sources, each the authority for a different thing.** The **wiki** owns identity and the
world, including the one fact per song that is the reason a DJ has anything to say. The **lyrics
files** own provenance, resolved song block first and album block second by `tag.py` (D-062). The
**audio** owns the mixer's three numbers, *measured* by `analyse.py` on every run rather than
cached, because a re-generated take under the same name is what a stored number gets wrong (M-04).

**`playable` means the audio exists, and nothing else** (§8, D-044). A layer-B title — a record the
world knows and the station does not hold — is an unplayable row, and so is a layer-A song whose
Suno card has not run yet; the two are indistinguishable here on purpose, because what rotation
needs to know is whether there is a file, and the difference disappears when the last genre is
generated. `file`, `duration_sec`, `intro_ramp_sec`, `outro_type`, `licence_note` and `category`
are null wherever `playable` is false — §8's invariant, in the row rather than in a convention.

**`category` is derived, not chosen** (D-085): §8 defines `gold` as five in-world years old or more,
everything else here is `A`, and `new`, `B`, `C` and `specialist` are never written. An age is a
fact about the present, so the present year is in the file and `catalogue_check.py` reads it back.
"""

from __future__ import annotations

import re
from collections import Counter
from collections.abc import Callable
from pathlib import Path

import yaml
from pydantic import BaseModel, Field, ValidationError

from station import log
from station.music import analyse, tag, wiki

CATALOGUE_FILE = "catalogue.yaml"  # under `music/`
LANGUAGE = "en"

# §8's rotation weights. `gold` is "catalogue, >=5 in-world years old"; `A` is heavy rotation.
GOLD_AFTER_YEARS = 5
HEAVY, GOLD = "A", "gold"

ALBUM_KINDS = frozenset({"album", "ep", "single", "live"})

# §8 gives `artists.kind` three values and the wiki writes six. A crew, a duo and a partnership are
# all several people who make records together, which is what `group` means in the column.
ARTIST_KINDS = {"solo": "solo", "group": "group", "collective": "collective",
                "crew": "group", "duo": "group", "partnership": "group"}  # fmt: skip

_LABEL_ID = re.compile(r"^label_\d+$")

HEADER = """\
# music/catalogue.yaml — the one file the station's database ingests (ARCHITECTURE §17a).
#
# GENERATED BY `make music-catalogue`, never hand-edited: the next run overwrites it whole and
# `make check` goes red the moment it stops agreeing with music/wiki/. A track carries the mixer's
# measured numbers and the licence its take was made under, and all of that is null wherever there
# is no audio — whether the record was never pressed in the world or its Suno card has not run yet.
# Why `category` holds only `A` and `gold`: src/station/music/catalogue.py, and D-085.

"""

logger = log.get_logger(job="music-catalogue")


class CatalogueError(RuntimeError):
    """The catalogue could not be built or read. The message names the file or id to fix."""


# --- the shape §17a fixes -------------------------------------------------------------------


class Label(BaseModel):
    id: str
    name: str
    settlement: str
    founded_year: int | None
    defunct_year: int | None
    house_style: str | None


class Artist(BaseModel):
    id: str
    name: str
    kind: str
    figure: str | None
    label: str | None
    settlement: str
    scene: str
    active_from: int
    active_to: int | None
    bio: str


class Album(BaseModel):
    id: str
    artist: str
    label: str | None
    title: str
    release_year: int
    kind: str
    cornerstone: bool
    notes: str


class Track(BaseModel):
    id: str
    album: str
    artist: str
    title: str
    track_no: int
    playable: bool
    file: str | None
    duration_sec: float | None
    intro_ramp_sec: float | None
    outro_type: str | None
    category: str | None
    mood: list[str]
    language: str
    licence_note: str | None
    fact: str | None


class Catalogue(BaseModel):
    version: int = 1
    present_year: int
    labels: list[Label]
    artists: list[Artist]
    albums: list[Album]
    tracks: list[Track]


class Take(BaseModel):
    """One song's audio, once it has been found on disk and measured."""

    file: str
    licence_note: str
    duration_sec: float
    intro_ramp_sec: float
    outro_type: str


class Build(BaseModel):
    """What one pass produced, and everything about it the operator should see."""

    catalogue: Catalogue
    unmeasurable: list[str] = Field(default_factory=list)
    unlabelled: dict[str, int] = Field(default_factory=dict)
    problems: list[str] = Field(default_factory=list)


# --- reading the three sources --------------------------------------------------------------


def genres(wiki_dir: Path) -> dict[str, wiki.GenreWiki]:
    """Every wiki file read — genres and collections both — or a failure naming the bad one."""
    try:
        found = {
            slug: wiki.load_genre(wiki_dir / f"{slug}.yaml")
            for slug in wiki.written_slugs(wiki_dir)
        }
    except wiki.WikiError as exc:
        raise CatalogueError(str(exc)) from None
    if not found:
        raise CatalogueError(f"no genre has been written under {wiki_dir} (music/RUNBOOK.md)")
    return found


def present_year(found: dict[str, wiki.GenreWiki]) -> int:
    """The in-world present, from the wiki because that is where it is written. All nine must agree —
    `gold` is an age, and two ages make one record catalogue in one genre and current in another."""
    years = sorted({g.section.present_year for g in found.values() if g.section.present_year})
    if len(years) != 1:
        stated = ", ".join(str(y) for y in years) or "nothing"
        raise CatalogueError(
            f"the genre files state {stated} as `section.present_year` and it has to be one year "
            f"(music/CONSTANTS.md §1: the present is the real year plus six hundred)"
        )
    return years[0]


def takes(music: Path) -> dict[str, tag.Song]:
    """Song id → the take recorded for it, with the licence already resolved (D-062)."""
    try:
        return {song.song_id: song for song in tag.load_songs(music)}
    except tag.TagError as exc:
        raise CatalogueError(f"the takes cannot say what they were made under — {exc}") from None


def measure(
    root: Path, recorded: dict[str, tag.Song], on_measured: Callable[[], None] | None = None
) -> tuple[dict[str, Take], list[str]]:
    """Measure every take on disk. §25's ffprobe rule: one that cannot be read is marked unusable and
    reported, never given a silent ramp of zero — that is the link clipping the first sung word."""
    measured: dict[str, Take] = {}
    failed: list[str] = []
    for song_id, song in sorted(recorded.items()):
        if not song.path.is_file():
            continue
        try:
            one = analyse.measure(song.path)
        except analyse.AnalyseError as exc:
            logger.error("unmeasurable", song=song_id, path=str(song.path), error=str(exc))
            failed.append(f"{song_id}: {exc}")
            continue
        measured[song_id] = Take(
            file=song.path.relative_to(root).as_posix(),
            licence_note=song.provenance.licence_period,
            duration_sec=one.duration_sec,
            intro_ramp_sec=one.intro_ramp_sec,
            outro_type=one.outro_type,
        )
        if on_measured is not None:
            on_measured()
    return measured, failed


# --- turning the wiki into rows ---------------------------------------------------------------


def _label_id(reference: str, unlabelled: Counter[str]) -> str | None:
    """`unsigned`, `not imported` and `not for sale` are the wiki's three ways of saying no house.
    Every unresolved reference is counted, so a typo shows up instead of becoming a silent null."""
    if _LABEL_ID.match(reference):
        return reference
    if reference.isdigit():
        return f"label_{reference}"
    if reference:
        unlabelled[reference] += 1
    return None


def _figure(band: wiki.Band) -> str | None:
    """§8 makes an artist a figure — which is only true of a solo act the wiki actually names."""
    if ARTIST_KINDS.get(band.kind) != "solo" or len(band.members) != 1:
        return None
    return band.members[0].id or None


def _labels(found: dict[str, wiki.GenreWiki]) -> list[Label]:
    """The seven houses, merged: every genre a label presses repeats its entry, in varying detail."""
    merged: dict[str, Label] = {}
    for genre in found.values():
        for entry in genre.labels:
            was = merged.get(entry.id)
            merged[entry.id] = Label(
                id=entry.id,
                name=entry.name,
                settlement=entry.home or (was.settlement if was else ""),
                founded_year=entry.founded_year or (was.founded_year if was else None),
                defunct_year=entry.folded_year or (was.defunct_year if was else None),
                house_style=was.house_style if was else None,  # no genre file states one
            )
    return sorted(merged.values(), key=lambda x: x.id)


def _artists(found: dict[str, wiki.GenreWiki]) -> tuple[list[Artist], Counter[str]]:
    """Every band in both layers. A layer-B band still made the records its titles belong to."""
    out: list[Artist] = []
    unlabelled: Counter[str] = Counter()
    for slug, genre in sorted(found.items()):
        for band in genre.layer_a.bands + genre.layer_b.bands:
            out.append(
                Artist(
                    id=band.id,
                    name=band.name,
                    kind=ARTIST_KINDS.get(band.kind, band.kind),
                    figure=_figure(band),
                    label=_label_id(band.label, unlabelled),
                    settlement=band.home_settlement,
                    scene=slug,
                    active_from=band.active_from,
                    active_to=band.active_to,
                    bio=band.bio,
                )
            )
    return sorted(out, key=lambda x: x.id), unlabelled


def _artist_id(album: wiki.Album, band: wiki.Band | None) -> str:
    """Layer A points at its band; layer B nests inside it. Both placements occur (`every_album`)."""
    return album.band or (band.id if band else "")


def _albums(found: dict[str, wiki.GenreWiki]) -> tuple[list[Album], Counter[str]]:
    out: list[Album] = []
    unlabelled: Counter[str] = Counter()
    for genre in found.values():
        for album, band, _ in genre.every_album():
            out.append(
                Album(
                    id=album.id,
                    artist=_artist_id(album, band),
                    label=_label_id(album.label, unlabelled),
                    title=album.title,
                    release_year=album.release_year,
                    kind=album.kind.lower(),
                    cornerstone=album.cornerstone,
                    notes=album.notes,
                )
            )
    return sorted(out, key=lambda x: x.id), unlabelled


def _category(release_year: int, present: int) -> str:
    return GOLD if present - release_year >= GOLD_AFTER_YEARS else HEAVY


def _tracks(
    found: dict[str, wiki.GenreWiki], present: int, measured: dict[str, Take]
) -> tuple[list[Track], list[str]]:
    out: list[Track] = []
    problems: list[str] = []
    for slug, genre in sorted(found.items()):
        for album, band, layer in genre.every_album():
            for song in album.songs:
                take = measured.get(song.id)
                if take is not None and layer == "B":
                    problems.append(
                        f"{slug}: {song.id} is a layer-B title and has audio at {take.file} — "
                        f"layer B is what the world knows and the station does not hold"
                    )
                out.append(
                    Track(
                        id=song.id,
                        album=album.id,
                        artist=_artist_id(album, band),
                        title=song.title,
                        track_no=song.track_number,
                        playable=take is not None,
                        file=take.file if take else None,
                        duration_sec=take.duration_sec if take else None,
                        intro_ramp_sec=take.intro_ramp_sec if take else None,
                        outro_type=take.outro_type if take else None,
                        category=_category(album.release_year, present) if take else None,
                        mood=list(song.mood_tags),
                        language=LANGUAGE,
                        licence_note=take.licence_note if take else None,
                        fact=(song.fact or "").strip() or None,
                    )
                )
    return sorted(out, key=lambda x: x.id), problems


# --- the pass -------------------------------------------------------------------------------


def build(root: Path, on_measured: Callable[[], None] | None = None) -> Build:
    """The whole catalogue, measured from the audio that exists today."""
    music = root / "music"
    found = genres(music / wiki.WIKI_DIR)
    present = present_year(found)
    measured, unmeasurable = measure(root, takes(music), on_measured)
    artists, unlabelled = _artists(found)
    albums, album_unlabelled = _albums(found)
    unlabelled.update(album_unlabelled)
    tracks, problems = _tracks(found, present, measured)
    logger.debug("built", present_year=present, tracks=len(tracks), playable=len(measured))
    return Build(
        catalogue=Catalogue(
            present_year=present,
            labels=_labels(found),
            artists=artists,
            albums=albums,
            tracks=tracks,
        ),
        unmeasurable=unmeasurable,
        unlabelled=dict(unlabelled.most_common()),
        problems=problems,
    )


def write(path: Path, catalogue: Catalogue) -> None:
    """Replace the file whole. There is no partial catalogue worth keeping."""
    body = yaml.safe_dump(
        catalogue.model_dump(),
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=100,
    )
    path.write_text(HEADER + body, encoding="utf-8")


def load(path: Path) -> Catalogue:
    """Read the file back, or fail naming it."""
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise CatalogueError(f"missing {path} — run `make music-catalogue`") from None
    except yaml.YAMLError as exc:
        raise CatalogueError(f"{path} is not valid YAML: {exc}") from None
    try:
        return Catalogue.model_validate(raw)
    except ValidationError as exc:
        raise CatalogueError(f"{path} is not the shape ARCHITECTURE §17a fixes:\n{exc}") from None
